apiVersion: v1
kind: Service
metadata:
  name: engagement-service
  namespace: quetxal-tv-prod
spec:
  type: ClusterIP
  selector:
    app: engagement-service
  ports:
    - name: grpc
      port: 50056
      targetPort: 50056
