apiVersion: v1
kind: Service
metadata:
  name: fx-service
  namespace: quetxal-tv-prod
spec:
  type: ClusterIP
  selector:
    app: fx-service
  ports:
    - name: grpc
      port: 50052
      targetPort: 50052
