apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: quetxal-tv-prod
spec:
  type: ClusterIP
  selector:
    app: identity-service
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
