apiVersion: v1
kind: Service
metadata:
  name: payment-gateway-service
  namespace: quetxal-tv-prod
spec:
  type: ClusterIP
  selector:
    app: payment-gateway-service
  ports:
    - name: grpc
      port: 50057
      targetPort: 50057
