apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: quetxal-tv-frontend-config
  namespace: quetxal-tv-prod
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
